### ISSUE TITLE
Nernia giveing crash reports everytime when joining

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#225]
### Crash Summary

When joining a sever i always get Nernia errors when i join. Recently on one of my severs i have been getting a lot of crashes no mater the amount of ram I allocate.

### Steps to Reproduce

I just played on a sever for long enough it started happening

### Involved Mods

¯\_(ツ)_/¯

### Crash Log

![Image](https://github.com/user-attachments/assets/9bde615f-e51f-4fe7-9f2e-10fedd59d343)
[Nernia logs 1.txt](https://github.com/user-attachments/files/20027511/Nernia.logs.1.txt)

---------------------

This is on a second server im running and im recently gotten the same issue (tho the sever is not crashing) But both of the crash logs are identical for both mobs

![Image](https://github.com/user-attachments/assets/3ec80248-408f-4df6-9821-ace9a066c627)

[Nernia logs 2.txt](https://github.com/user-attachments/files/20027531/Nernia.logs.2.txt)

**Comment by uthw** [comment]
Neruina basically suspends entities that were about to cause a server crash. When it does this, it locks the entity in place and makes it unable to do anything or be attacked, so this isn't really a crash.

We'll need to go on a case-by-case basis here since there's no solution that fixes all ticking entities. I know about the ones with pillagers (which is what both the attached errors are talking about) and it seems like that'll be fixed in the next Savage & Ravage update. If you could provide the one for the soul sprout I'd be able to investigate and see if I can fix it.

**Comment by Guineapigboyx** [comment]
I put it as a crash since I thoght a entity crash is still a crash.

I will send you the IP for the server is (in your dms)

Idk anything else about the soul sprout.

**Comment by uthw** [comment]
Shouldn't be as bad anymore since Neruina will kill the ticking entity in 0.5.0, see #231 for more details on the pillager one
